# 第二章 NumPy基础

In [1]:
import numpy as np
import numpy

### 1.Numpy数组对象

In [2]:
a=np.arange(5)
a.dtype

dtype('int32')

In [3]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.shape

(5,)

In [7]:
m =np.array([np.arange(2), np.arange(2)])
print(m)

[[0 1]
 [0 1]]


In [9]:
a = np.array([[1,2],[3,4]])
print(a[0,0])
print(a[0,1])
print(a[1,0])
print(a[1,1])

1
2
3
4


### 2.Numpy数据类型

In [11]:
#Python支持的数据类型有整型、浮点型以及复数型
#numpy中的数据类型
#bool inti int8  int16 int32 int64
#uint8 uint16 uint32 uint64
#float16 float32 float64或float
#complex64  complex128或者complex

In [15]:
print(np.float64(42))
print(np.int8(42.0))
print(np.bool(42))
print(np.bool(0))
print(np.float(True))
print(np.float(False))
#复数不可以转换为整数和浮点数,但是整数和浮点数可以转换为复数这会引发一个TypeError错误

42.0
42
True
False
1.0
0.0


In [16]:
a=np.arange(7,dtype=np.uint16)
print(a.dtype)

uint16


### 3.数据类型对象

In [17]:
a.dtype.itemsize

2

### 4.字符编码

In [18]:
#字符编码,此方法不推荐
#i(整数) u(无符号整数) f(单精度浮点数)
#d(双精度浮点数) b(布尔值) D(复数) S(字符串) U(unicode字符串) V(void空)

In [20]:
np.arange(7,dtype="f")

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [21]:
np.arange(7,dtype="D")

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

### 5.自定义数据类型

In [28]:
#可以使用Python中的浮点数类型：
np.dtype(float)

dtype('float64')

In [29]:
#可以使用字符编码来指定单精度浮点数类型：
np.dtype('f')

dtype('float32')

In [30]:
#可以使用字符编码来指定双精度浮点数类型：
np.dtype('d')

dtype('float64')

In [31]:
#还可以将两个字符作为参数传给数据类型的构造函数。此时，第一个字符表示数据类型，
#第二个字符表示该类型在内存中占用的字节数（2、4、8分别代表精度为16、32、64位的
#浮点数）：
np.dtype('f8')

dtype('float64')

In [33]:
#完整的NumPy数据类型列表可以在 sctypeDict.keys() 中找到：
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'int64', 'Int64', 'i8', 'uint64', 'UInt64', 'u8', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 

### 6.dtype 类的属性

In [35]:
#dtype 类有很多有用的属性。例如，我们可以获取数据类型的字符编码：
t=np.dtype('Float64')
t.char

C:\Users\zsx\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  


'd'

In [36]:
#type 属性对应于数组元素的数据类型：
t.type

numpy.float64

In [38]:
#str 属性可以给出数据类型的字符串表示，该字符串的首个字符表示字节序（endianness），
#后面如果还有字符的话，将是一个字符编码，接着一个数字表示每个数组元素存储所需的字节数。
#这里，字节序是指位长为32或64的字（word）存储的顺序，包括大端序（big-endian）和小端序
#（little-endian）。大端序是将最高位字节存储在最低的内存地址处，用 > 表示；与之相反，小端序
#是将最低位字节存储在最低的内存地址处，用 < 表示
t.str

'<f8'

### 7.创建自定义数据类型

In [39]:
#自定义数据类型是一种异构数据类型，可以当做用来记录电子表格或数据库中一行数据的结构。

In [42]:
#(1) 创建数据类型：
t=np.dtype([('name',np.str_,40),('numitems',np.int32),('price',np.float32)])

In [43]:
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [44]:
#(2) 查看数据类型（也可以查看某一字段的数据类型）
t['name']

dtype('<U40')

In [46]:
#在用 array 函数创建数组时，如果没有在参数中指定数据类型，将默认为浮点数类型。而现
#在，我们想要创建自定义数据类型的数组，就必须在参数中指定数据类型，否则将触发 TypeError
#错误：
items=np.array([('meaning of life DVD',42,3.14),('Butter',13,2.72)],dtype=t)
items[1]

('Butter', 13, 2.72)

### 8.一维数组的索引和切片

In [68]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
a[3:7]

array([3, 4, 5, 6])

In [70]:
a[:7:2]

array([0, 2, 4, 6])

In [71]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

### 9.多维数组的切片和索引

In [48]:
#ndarray 支持在多维数组上的切片操作。为了方便起见，我们可以用一个省略号（ ... ）来
#表示遍历剩下的维度

In [52]:
b=np.arange(24).reshape(2,3,4)
b.shape

(2, 3, 4)

In [53]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
b[1,1,1]

17

In [55]:
b[:,0,0]

array([ 0, 12])

In [56]:
b[0,:,:]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
b[0,1]

array([4, 5, 6, 7])

In [61]:
b[0,1,::2]

array([4, 6])

In [63]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [64]:
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [66]:
b[0,:,-1]

array([ 3,  7, 11])

In [67]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### 10.改变数组的维度

In [72]:
#(1) ravel 我们可以用 ravel 函数完成展平的操作：
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [73]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
#(2) flatten 这个函数恰如其名， flatten 就是展平的意思，与 ravel 函数的功能相同。
#不过， flatten 函数会请求分配内存来保存结果，而 ravel 函数只是返回数组的一个视图（view）：
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [80]:
#(3) 用元组设置维度 除了可以使用 reshape 函数，我们也可以直接用一个正整数元组来设
#置数组的维度，如下所示
b.shape = (6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
#(4) transpose 在线性代数中，转置矩阵是很常见的操作。对于多维数组，我们也可以这样做：
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [78]:
#(5) resize和 reshape 函数的功能一样，但 resize 会直接修改所操作的数组：
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### 11.数组的组合

In [82]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
b=a*2
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [89]:
#(1) 水平组合 我们先从水平组合开始练习。将 ndarray 对象构成的元组作为参数，传给
#hstack 函数。
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [91]:
#我们也可以用 concatenate 函数来实现同样的效果
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [93]:
#(2) 垂直组合 垂直组合同样需要构造一个元组作为参数，只不过这次的函数变成了vstack 。
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [94]:
#同样，我们将 concatenate 函数的 axis 参数设置为0即可实现同样的效果。这也是 axis 参
#数的默认值：
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [95]:
#(3) 深度组合 将相同的元组作为参数传给 dstack 函数，即可完成数组的深度组合。所谓
#深度组合，就是将一系列数组沿着纵轴（深度）方向进行层叠组合。
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [97]:
#(4) 列组合 column_stack 函数对于一维数组将按列方向进行组合，如下所示：
oned=np.arange(2)
print(oned)
twice_oned=2*oned
print(twice_oned)
np.column_stack((oned,twice_oned))

[0 1]
[0 2]


array([[0, 0],
       [1, 2]])

In [98]:
#而对于二维数组， column_stack 与 hstack 的效果是相同的
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [105]:
np.column_stack((a, b)) ==np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [100]:
#(5) 行组合 当然，NumPy中也有按行方向进行组合的函数，它就是 row_stack 。对于两
#个一维数组，将直接层叠起来组合成一个二维数组。
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [104]:
#对于二维数组， row_stack 与 vstack 的效果是相同的：
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [106]:
np.row_stack((a, b)) ==np.vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 12.数组的分割

In [107]:
#NumPy数组可以进行水平、垂直或深度分割，相关的函数有 hsplit 、 vsplit 、 dsplit 和
#split 。我们可以将数组分割成相同大小的子数组，也可以指定原数组中需要分割的位置

In [109]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
#(1) 水平分割 下面的代码将把数组沿着水平方向分割为3个相同大小的子数组：
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [110]:
#对同样的数组，调用 split 函数并在参数中指定参数 axis=1 ，对比一下结果：
np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [111]:
#(2) 垂直分割 vsplit 函数将把数组沿着垂直方向分割：
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [112]:
#同样，调用 split 函数并在参数中指定参数 axis=0 ，也可以得到同样的结果：
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [113]:
#(3) 深度分割 不出所料， dsplit 函数将按深度方向分割数组。我们先创建一个三维数组：
c=np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [114]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### 13.数组的属性

In [115]:
#除了 shape 和 dtype 属性以外， ndarray 对象还有很多其他的属性，在下面一一列出。

In [119]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [120]:
#ndim 属性，给出数组的维数，或数组轴的个数：
b.ndim

2

In [121]:
#size 属性，给出数组元素的总个数，如下所示：
b.size

9

In [122]:
#itemsize 属性，给出数组中的元素在内存中所占的字节数：
b.itemsize

4

In [124]:
#如果你想知道整个数组所占的存储空间，可以用 nbytes 属性来查看。这个属性的值其实
#就是 itemsize 和 size 属性值的乘积：
b.nbytes

36

In [125]:
#T 属性的效果和 transpose 函数一样，如下所示：
b.T

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

In [126]:
#对于一维数组，其 T 属性就是原数组
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [127]:
a.T

array([0, 1, 2, 3, 4])

In [129]:
a.ndim

1

In [130]:
#在NumPy中，复数的虚部是用 j 表示的。例如，我们可以创建一个由复数构成的数组：
d=np.array([1+2.j,2.j+3])

In [131]:
d

array([1.+2.j, 3.+2.j])

In [133]:
#real 属性，给出复数数组的实部。如果数组中只包含实数元素，则其 real 属性将输出原数组：
d.real

array([1., 3.])

In [135]:
#imag 属性，给出复数数组的虚部：
d.imag

array([2., 2.])

In [136]:
#如果数组中包含复数元素，则其数据类型自动变为复数型：
d.dtype

dtype('complex128')

In [137]:
d.dtype.str

'<c16'

In [138]:
#flat 属性将返回一个 numpy.flatiter 对象，这是获得 flatiter 对象的唯一方式——我
#们无法访问 flatiter 的构造函数。这个所谓的“扁平迭代器”可以让我们像遍历一维数
#组一样去遍历任意的多维数组，如下所示：
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [139]:
f = b.flat
f

In [142]:
for item in f: 
    print (item)

0
1
2
3


In [143]:
#我们还可以用 flatiter 对象直接获取一个数组元素：
b.flat[2]

2

In [144]:
#或者获取多个元素：
b.flat[[1,3]]

array([1, 3])

In [145]:
#flat 属性是一个可赋值的属性。对 flat 属性赋值将导致整个数组的元素都被覆盖：
b.flat = 7
b

array([[7, 7],
       [7, 7]])

In [146]:
b.flat[[1,3]] = 1
b

array([[7, 1],
       [7, 1]])

### 14.数组的转换

In [147]:
#我们可以使用 tolist 函数将NumPy数组转换成Python列表。

In [148]:
b.tolist()

[[7, 1], [7, 1]]

In [150]:
b=np.array([ 1.+1.j, 3.+2.j])
b.tolist()

[(1+1j), (3+2j)]

In [151]:
b.astype(int)

C:\Users\zsx\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1, 3])

In [152]:
#在上面将复数转换为整数的过程中，我们丢失了复数的虚部。 astype 函数
#也可以接受数据类型为字符串的参数。
b.astype('complex')

array([1.+1.j, 3.+2.j])